apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  labels:
    app: kmp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host:
      http:
        paths:
          - path: /*
            backend:
              serviceName: frontend
              servicePort: 80
          - path: /api/*
            backend:
              serviceName: backend
              servicePort: 3000
